language: node_js
node_js:
    - "8"
deploy:
  provider: script
  script: wget https://raw.githubusercontent.com/miscord/build-scripts/master/make.sh && chmod +x make.sh && bash make.sh
  on:
    branch: master